build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - gcc -O3 -std=c99 -o f float-lenet.c

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - grep label float_images.h|cut -d' ' -f 3 > truth
    - rm -f predictions
    - for i in $(seq 0 7) ; do ./f $i|tail -1|cut -d' ' -f 3 >> predictions; done
    - diff truth predictions
